version: '3.1'

services:
  db:
    image: mspbgx/centos-mariadb
    restart: always
    volumes:
      - /opt/docker/nextcloud/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ABC123xyz
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=ABC123xyz

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /opt/docker/nextcloud/data/app:/var/www/html
    restart: always
